/* =========================================================================
   TRIVIA TRAIL — QUESTION DATABASE
   Edit this file freely. Each color key holds a list of {q, a} pairs.
   Add as many as you like per category.

     blue   -> The Office: Characters
     pink   -> The Office: Quotes
     yellow -> The Office: Trivia
     green  -> Curb Your Enthusiasm: Characters
     orange -> Curb Your Enthusiasm: Quotes
     purple -> Curb Your Enthusiasm: Trivia

   Generated from Trivia_Trail_Questions.xlsx — unanswered questions only
   (rows with a value in the "Answered" column are excluded).

   This file must be loaded BEFORE the game script (index.html already does
   this with <script src="questions.js"></script>).
   ========================================================================= */
window.QUESTIONS = {

  // ===== The Office — Characters (57) =====
  blue: [
    { q: "Who plays Michael Scott?", a: "Steve Carell" },
    { q: "Who plays Jim Halpert?", a: "John Krasinski" },
    { q: "Who plays Pam Beesly?", a: "Jenna Fischer" },
    { q: "Who plays Dwight Schrute?", a: "Rainn Wilson" },
    { q: "Who plays Andy Bernard?", a: "Ed Helms" },
    { q: "Who plays Kevin Malone?", a: "Brian Baumgartner" },
    { q: "Who plays Angela Martin?", a: "Angela Kinsey" },
    { q: "Who plays Oscar Martinez?", a: "Oscar Nuñez" },
    { q: "Who plays Stanley Hudson?", a: "Leslie David Baker" },
    { q: "Who plays Phyllis Vance?", a: "Phyllis Smith" },
    { q: "Who plays Meredith Palmer?", a: "Kate Flannery" },
    { q: "Who plays Ryan Howard?", a: "B.J. Novak" },
    { q: "Who plays Kelly Kapoor?", a: "Mindy Kaling" },
    { q: "Who plays Toby Flenderson?", a: "Paul Lieberstein" },
    { q: "Who plays Darryl Philbin?", a: "Craig Robinson" },
    { q: "Who plays Erin Hannon?", a: "Ellie Kemper" },
    { q: "Who plays Gabe Lewis?", a: "Zach Woods" },
    { q: "Who plays Holly Flax?", a: "Amy Ryan" },
    { q: "Who plays Jan Levinson?", a: "Melora Hardin" },
    { q: "Who plays Roy Anderson?", a: "David Denman" },
    { q: "Who plays David Wallace?", a: "Andy Buckley" },
    { q: "Who plays Robert California?", a: "James Spader" },
    { q: "Who plays Nellie Bertram?", a: "Catherine Tate" },
    { q: "Who plays Charles Miner?", a: "Idris Elba" },
    { q: "Who plays Deangelo Vickers?", a: "Will Ferrell" },
    { q: "Who plays Todd Packer?", a: "David Koechner" },
    { q: "Who plays Karen Filippelli?", a: "Rashida Jones" },
    { q: "Who plays Jo Bennett?", a: "Kathy Bates" },
    { q: "Who plays Helene Beesly?", a: "Linda Purl" },
    { q: "Who does Holly date from the Nashua Branch?", a: "AJ" },
    { q: "What is the name of the tech support employee that Michael mistakes for a terrorist?", a: "Sadiq" },
    { q: "What is Dwight's full name, including middle name and suffix?", a: "Dwight Kurt Schrute III" },
    { q: "What is Michael's middle name?", a: "Gary" },
    { q: "What is Erin's actual first name?", a: "Kelly" },
    { q: "What is Robert California's birth name?", a: "Bob Kazamakis" },
    { q: "What is Phyllis's maiden name before marrying Bob Vance?", a: "Lapin" },
    { q: "What are the names of Jim and Pam's two children?", a: "Cecelia (Cece) and Philip" },
    { q: "What is the name of Jan's baby, conceived via sperm donor?", a: "Astrid" },
    { q: "What state senator does Angela marry?", a: "Robert Lipton" },
    { q: "What is the name of Michael's realtor girlfriend who has kids and an ex-husband?", a: "Carol" },
    { q: "Who is Roy's brother that helps him confront Jim?", a: "Kenny" },
    { q: "Which warehouse worker becomes Darryl's love interest?", a: "Val" },
    { q: "What is the Scranton Strangler suspect's name?", a: "George Howard Skub" },
    { q: "Which documentary crew member becomes a brief love interest for Pam?", a: "Brian" },
    { q: "What is the name of Dwight's brother?", a: "Jeb" },
    { q: "What is the name of Dwight's sister?", a: "Fannie" },
    { q: "What is the name of Dwight's nephew?", a: "Cameron Whitman" },
    { q: "What is the name of Dwight's babysitter/date whom he brings to Michael's dinner party?", a: "Melvina" },
    { q: "What is the name of Carol's ex-husband?", a: "Steve" },
    { q: "What is the name of the woman Michael dates who owns the bar?", a: "Donna" },
    { q: "What is the name of Michael's nephew whom he hires as an office assistant?", a: "Luke Cooper" },
    { q: "What is the name of Michael's imaginary childhood friend?", a: "Jeff" },
    { q: "What is the name of the booze cruise captain?", a: "Captain Jack" },
    { q: "What is the name of Jim's boss at the Stamford branch?", a: "Josh Porter" },
    { q: "What is the name of the paper mill employee Creed gets fired when inappropriate images appear on paper?", a: "Debbie Brown" },
    { q: "Who does the senator publicly announce he is in love with?", a: "Wesley Silver" },
    { q: "Who hits Toby in the eye during the paper airplane competition?", a: "Pam" }
  ],

  // ===== The Office — Quotes (38) =====
  pink: [
    { q: "Complete the Michael quote: 'I'm not superstitious, ___'", a: "but I am a little stitious" },
    { q: "Complete the Michael quote: 'I DECLARE ___'", a: "BANKRUPTCY!" },
    { q: "Complete the Michael quote: 'Would I rather be feared or loved? Easy. Both. I want people ___'", a: "to be afraid of how much they love me." },
    { q: "Complete the Michael quote: 'I knew exactly what to do. But in a much more real sense, ___'", a: "I had no idea what to do." },
    { q: "Complete the Michael quote: 'I am ___, always.'", a: "Beyoncé" },
    { q: "Complete the Stanley quote: 'Boy, have you lost your mind? ___'", a: "Cause I'll help you find it." },
    { q: "Complete the Michael quote: 'I love inside jokes. ___'", a: "I'd love to be a part of one someday." },
    { q: "Complete the Michael quote: 'Toby is in HR, which technically means he works for corporate, so he's really not a part of our family. Also, ___'", a: "he's divorced, so he's really not a part of his family." },
    { q: "Complete the Michael quote: 'I'm an early bird and I'm a night owl. So ___'", a: "I'm wise and I have worms." },
    { q: "Complete the Michael quote: 'Dwight, ___'", a: "You ignorant slut" },
    { q: "Complete the Michael quote: 'You don't call retarded people retards. It's bad taste. You ___'", a: "call your friends retards when they're acting retarded." },
    { q: "Complete the Dwight quote: 'R is among the most menacing of sounds. That's why they call it murder, not ___'", a: "muckduck" },
    { q: "Complete the Dwight quote: 'Whenever I'm about to do something, I think, would an ___ do that? And if they would, I do not do that thing.'", a: "idiot" },
    { q: "Complete the Dwight quote: 'Through concentration, I can raise and lower my ___ at will'", a: "cholesterol" },
    { q: "Complete the Dwight quote: 'The eyes are the ___'", a: "groin of the head" },
    { q: "Complete the Dwight quote: 'You couldn't handle my ___'", a: "undivided attention" },
    { q: "Complete the Jim quote: 'Fact: ___'", a: "Bears eat beets. Bears. Beets. Battlestar Galactica" },
    { q: "Complete the Jim quote: 'Right now this is just a job. If I advance any higher in this company, then this would be my career. And if this were my career, ___'", a: "I'd have to throw myself in front of a train" },
    { q: "Complete the Pam quote: 'I feel ___ in this Chili's tonight.'", a: "God" },
    { q: "Complete the Kevin quote: 'Why waste time say lot word when ___?'", a: "few word do trick" },
    { q: "Complete the Kevin quote: 'I just want to lie on the beach and ___. That's all I've ever wanted.'", a: "eat hot dogs" },
    { q: "Complete the Creed quote: 'If I can't ___, then what's this all been about? What am I working toward?'", a: "scuba" },
    { q: "Complete the Stanley quote: 'Did I ___'", a: "stutter?" },
    { q: "Complete the Dwight quote: 'How would I describe myself? Three words: ___'", a: "hard-working, alpha male, jackhammer, merciless, insatiable." },
    { q: "Complete the Phyllis quote: 'Close your mouth sweetie. You look like a ___'", a: "Trout" },
    { q: "Complete the Pam quote: 'No, no... cause then the ice melts and it's like ___'", a: "second drink" },
    { q: "Complete the Michael quote: 'I want you to rub butter on my foot. Pam please! I have ___'", a: "Country Crock" },
    { q: "Complete the Kelly quote: 'Darryl Philbin is the most complicated man I've ever met. I mean... who says ___?'", a: "exactly what they're thinking" },
    { q: "Complete the Phyllis quote: 'I wonder what people like about me. Probably ___'", a: "my jugs" },
    { q: "Complete the Michael quote: 'Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way, like an improv conversation... ___'", a: "an improversation" },
    { q: "Complete the Kevin quote: 'I got six numbers. One more and it would have been ___'", a: "a complete phone number" },
    { q: "Complete the Creed quote: 'Oh, you're paying too much for ___, man. Who's your ___ guy?'", a: "worm" },
    { q: "Complete the Kelly quote: 'I talk a lot, so ___'", a: "I've learned to tune myself out" },
    { q: "Complete the Phyllis quote: 'As a person who buys a lot of ___, it just feels good to be represented on one.'", a: "erotic cakes" },
    { q: "Complete the Stanley quote: 'Life is short. Drive fast and ___. That's one of my mottos.'", a: "leave a sexy corpse" },
    { q: "Complete the Michael quote: 'You know what they say: fool me once, strike one. But fool me twice... ___'", a: "strike three" },
    { q: "Complete the Michael quote: 'I feel like all my kids grew up, and then they married each other. It's ___'", a: "every parent's dream" },
    { q: "Complete the Michael quote: 'Abraham Lincoln once said that, ___'", a: "If you're a racist, I will attack you with the North." }
  ],

  // ===== The Office — Trivia (68) =====
  yellow: [
    { q: "What Dundie does Pam win in the episode 'The Dundies'?", a: "Whitest Sneaker Award" },
    { q: "According to the song his employees sing, how many minutes has Michael worked at Dunder Mifflin?", a: "9,986,000" },
    { q: "What Pennsylvania county is Scranton located in (where Dwight is a volunteer sheriff's deputy)?", a: "Lackawanna County" },
    { q: "What company acquires Dunder Mifflin, bringing Jo Bennett and Gabe into the show?", a: "Sabre" },
    { q: "In what city is Sabre headquartered?", a: "Tallahassee, Florida" },
    { q: "What is the name of the bar the office frequents?", a: "Poor Richard's" },
    { q: "Which branch merges with Scranton in season 3, sending over Andy and Karen?", a: "Stamford" },
    { q: "What is Andy's a cappella group at Cornell called?", a: "Here Comes Treble" },
    { q: "What is Andy's self-appointed nickname?", a: "Nard Dog" },
    { q: "What is Creed's official job title at Dunder Mifflin?", a: "Director of Quality Assurance" },
    { q: "What candle business does Jan start in Michael's condo?", a: "Serenity by Jan" },
    { q: "What is the name of Michael's secret-agent character in Threat Level Midnight?", a: "Michael Scarn" },
    { q: "What is the villain's name, played by Jim in Threat Level Midnight?", a: "Goldenface" },
    { q: "How does Michael injure his foot in 'The Injury'?", a: "He grills it on a George Foreman grill" },
    { q: "What Office Olympics event involves shuffling in boxes of paper like snowshoes?", a: "Flonkerton" },
    { q: "In 'Scott's Tots,' what does Michael actually give the students instead of tuition?", a: "Laptop batteries" },
    { q: "What starts the office fire in the episode 'The Fire'?", a: "Ryan's cheese pita" },
    { q: "What song is the branch taught to give chest compressions to?", a: "Stayin' Alive" },
    { q: "Where are the Dundies held (until Michael gets the group kicked out)?", a: "Chili's" },
    { q: "What toy does David Wallace invent that makes him rich enough to buy back Dunder Mifflin?", a: "Suck It" },
    { q: "What is Kevin's Police cover band called?", a: "Scrantonicity" },
    { q: "What one prop does Michael insist on bringing into every scene of his improv class?", a: "A gun" },
    { q: "What is the name of the exclusive club Pam, Oscar, and Toby form?", a: "The Finer Things Club" },
    { q: "What company does Michael start after quitting, operating out of the same building?", a: "The Michael Scott Paper Company" },
    { q: "Where does Toby move at the end of season 4 before returning?", a: "Costa Rica" },
    { q: "On what jury does Toby serve?", a: "The Scranton Strangler trial" },
    { q: "What does the in-universe documentary turn out to be titled?", a: "The Office: An American Workplace" },
    { q: "What is the name of Angela's beloved cat that Dwight freezes?", a: "Sprinkles" },
    { q: "What 'memorial fun run' does Michael organize after hitting Meredith with his car?", a: "The Michael Scott's Dunder Mifflin Scranton Meredith Palmer Memorial Celebrity Rabies Awareness Fun Run Race for the Cure" },
    { q: "What ailment does Meredith contract after Michael's car accident?", a: "Rabies" },
    { q: "What is the name of the cat Dwight gives Angela?", a: "Garbage" },
    { q: "What food does Dwight bring to the dinner party in a large container?", a: "Beet salad" },
    { q: "What song does Hunter sing on the CD Jan plays during the dinner party?", a: "That One Night" },
    { q: "What object does Jan throw at Michael's plasma TV?", a: "A Dundie" },
    { q: "What is Michael's username on the dating website?", a: "LittleKidLover" },
    { q: "Where does Michael propose to Carol?", a: "Kelly's Diwali celebration" },
    { q: "On what occasion does Michael break up with Pam's mother?", a: "Her birthday" },
    { q: "What Dundie does Ryan receive?", a: "Hottest in the Office" },
    { q: "What Dundie does Kevin receive?", a: "Don't Go in There After Me" },
    { q: "What Dundie does Kelly receive?", a: "Spicy Curry Award" },
    { q: "What is the wedding date Roy announces on the Booze Cruise?", a: "June 10th" },
    { q: "What video game do the Stamford employees regularly play at work?", a: "Call of Duty" },
    { q: "What is Andy's username in the video game played at Stamford?", a: "Here Comes Treble" },
    { q: "What is Jim's username?", a: "JimHalpert" },
    { q: "What nickname does Andy repeatedly call Jim after meeting him?", a: "Big Tuna" },
    { q: "What nickname did Andy have in his college a cappella group?", a: "Boner Champ" },
    { q: "According to Kevin, what is the trick to his chili?", a: "Undercook the onions" },
    { q: "What does Creed grow in a desk drawer?", a: "Mung beans" },
    { q: "What does Dwight inherit from his Aunt Shirley?", a: "Her 80-acre beet farm" },
    { q: "Where does Angela buy clothes because the clothes at Gap Kids are too flashy?", a: "American Girl" },
    { q: "What is Creed's New Year's resolution?", a: "To do a cartwheel" },
    { q: "What does Michael say is the difference between a salesman and saleswoman", a: "Boobs" },
    { q: "Andy cannot remember the end of a jingle for what product?", a: "Kit Kat" },
    { q: "In the episode Gossip, what rumor does Michael spread about Pam?", a: "She is pregnant" },
    { q: "In the episode Gossip, what rumor does Michael spread about Andy?", a: "He is gay" },
    { q: "In the episode Gossip, what rumor does Michael spread about Angela?", a: "She is dating an 81 year old billionaire who owns a Quiznos franchise" },
    { q: "In the episode Gossip, what rumor does Michael spread about Kelly?", a: "She has an eating disorder/anorexia" },
    { q: "In the episode Gossip, what rumor does Michael spread about Dwight?", a: "He uses store-bought fertilizer/manure" },
    { q: "In the episode Gossip, what rumor does Michael spread about Creed?", a: "He has asthma" },
    { q: "In the episode Gossip, what rumor does Michael spread about Kevin?", a: "There is another smaller person inside of his body controlling him with controls" },
    { q: "In the episode Gossip, what rumor does Michael spread about Toby?", a: "He is a virgin" },
    { q: "During a morning paper delivery drive, Pam asks Michael for coffee and he hands her a thermos with what in it?", a: "Milk and Sugar" },
    { q: "Dwight claims paper is the manure and what is the soil in which the seeds of business grow?", a: "On-time delivery" },
    { q: "Who books the Honeymoon Suite the night before Jim and Pam's wedding?", a: "Andy" },
    { q: "What song does Andy dance to after making the warehouse workers leave?", a: "Footloose" },
    { q: "What was the name of the food truck outside the courthouse for both the Scranton Strangler trial and Jim's hit and run trial?", a: "Ernesto's" },
    { q: "What is Kevin's dogs name?", a: "Ruby" },
    { q: "What farm equipment does Henry Bruegger want to co-own with Dwight in exchange for letting him marry his daughter Esther?", a: "Auger" }
  ],

  // ===== Curb Your Enthusiasm — Characters (23) =====
  green: [
    { q: "Who plays Jeff Greene?", a: "Jeff Garlin" },
    { q: "Who plays Susie Greene?", a: "Susie Essman" },
    { q: "Who plays Leon Black?", a: "J.B. Smoove" },
    { q: "Who plays Marty Funkhouser?", a: "Bob Einstein" },
    { q: "Who plays Nat David?", a: "Shelley Berman" },
    { q: "Who plays Loretta Black?", a: "Vivica A. Fox" },
    { q: "Who plays Bam Bam Funkhouser, Marty's mental sister?", a: "Catherine O'Hara" },
    { q: "What is the name of Larry's manager and best friend?", a: "Jeff Greene" },
    { q: "What is the name of Jeff's wife?", a: "Susie Greene" },
    { q: "What is the first name of Jeff and Susie's daughter?", a: "Sammi" },
    { q: "What comedian plays himself as one of Larry's oldest friends?", a: "Richard Lewis" },
    { q: "Which actor plays himself and opens a restaurant with Larry?", a: "Ted Danson" },
    { q: "Who is Ted Danson's real-life wife, appearing as herself?", a: "Mary Steenburgen" },
    { q: "Who is Larry's accidental long-term houseguest?", a: "Leon Black" },
    { q: "Which outspoken comedian appears as herself as a friend of Larry?", a: "Wanda Sykes" },
    { q: "Who plays George Costanza?", a: "Jason Alexander" },
    { q: "Who plays Cosmo Kramer?", a: "Michael Richards" },
    { q: "Which actress does Jerry first suggest for the ex-wife role?", a: "Meg Ryan" },
    { q: "Which Back to the Future star feuds with Larry in season 8?", a: "Michael J. Fox" },
    { q: "Which legendary Goodfellas director appears as himself?", a: "Martin Scorsese" },
    { q: "Which 'Boss' musician guest-stars in the final season?", a: "Bruce Springsteen" },
    { q: "Which Friends star replaces Ben Stiller in 'The Producers'?", a: "David Schwimmer" },
    { q: "Who is Larry talking about when he says 'Everything is 'heaven' with him'?", a: "Ted Danson" }
  ],

  // ===== Curb Your Enthusiasm — Quotes (22) =====
  orange: [
    { q: "Who says: 'Get in that ass, Larry!'", a: "Leon Black" },
    { q: "Who says: 'Get the f*** out of my house, Larry!'", a: "Susie Greene" },
    { q: "Who says: 'If you're gonna be a maniac, pyro's not a good maniac.'", a: "Jeff Greene" },
    { q: "Who brags: 'I brings the ruckus to the ladies.'", a: "Leon Black" },
    { q: "Who snaps: 'F*** you... and f*** your tea.' after Larry rejects a sequined shirt?", a: "Susie Greene" },
    { q: "Who is famous for saving phone contacts under names like 'Nancy Big T**s'?", a: "Leon Black" },
    { q: "What does Larry call an unwanted sidewalk chat with an acquaintance?", a: "A stop and chat" },
    { q: "What does Larry call himself when saying rude truths for others?", a: "A social assassin" },
    { q: "What does Larry call cutting in line under cover of chatting with a friend?", a: "A chat and cut" },
    { q: "What does Larry demand people show his nice furniture?", a: "Respect the wood" },
    { q: "Complete the Larry quote: 'I don't like talking to... to ___, but ___, I have no problem with'", a: "People I know and strangers." },
    { q: "Complete the Larry quote: 'I guess I had a different plan for eternity.  I thought ___'", a: "I'd be single again" },
    { q: "Complete the Larry quote: 'It's hard to talk to a blind guy, you have ___'", a: "no references" },
    { q: "Who says: 'Do you crap standing up?'", a: "Marty Funkhouser" },
    { q: "Who says: 'That was a dry sneeze, Larry'", a: "Ben Stiller" },
    { q: "Complete the Larry quote: 'Here's a question for Who Wants to be a Millionaire - what kind of an idiot is running ___'", a: "ABC" },
    { q: "Who says: 'If you weren't my best friend I'd pop your head off'", a: "Marty Funhouser" },
    { q: "Who says: 'Not your business, Larry, you misanthropic moron'", a: "Susie Greene" },
    { q: "Who says: 'I can't STAND your water.  It's like I've stuck a straw up a frog's ass'", a: "Marty Funkhouser" },
    { q: "Who says: 'Had an uncle with a wobbly leg, couldn't stand that motherfucker, always leaning on shit!'", a: "Leon Black" },
    { q: "Who says: 'What - you scrounging around in the bleachers looking for asses?'", a: "Wanda Sykes" },
    { q: "Complete the Larry quote: 'I'm Larry David, and I happen to enjoy wearing ___'", a: "women's panties" }
  ],

  // ===== Curb Your Enthusiasm — Trivia (54) =====
  purple: [
    { q: "What is the satirical name of the hurricane that brings the Black family to Larry's home?", a: "Hurricane Edna" },
    { q: "In 'The Anonymous Donor,' who is actually responsible for the ejaculate stain on the blanket?", a: "Jeff" },
    { q: "In the season 7 premiere, Jeff sleeps with whose sister?", a: "Marty Funkhouser's" },
    { q: "Larry gets everyone kicked out of the country club after taking what out of Leo Funkhouser's coffin?", a: "A golf club (a 5-wood)" },
    { q: "What does Susie almost always wear, a running visual gag?", a: "Animal print" },
    { q: "In 'The Ski Lift,' Larry pretends to be Orthodox to get Richard Lewis what?", a: "A kidney" },
    { q: "What's wrong with Larry and Cheryl's second house?", a: "House sounds" },
    { q: "Why does Larry bring a sex worker to the baseball game?", a: "To use the carpool lane" },
    { q: "In season 2, what does Shaq try to count as a dairy product in Scattergories?", a: "Peanut Butter" },
    { q: "Which inappropriate birthday gift does Larry buy for Jennifer's son?", a: "A sewing machine" },
    { q: "What is the name of the Greenes' dog?", a: "Oscar" },
    { q: "How many shrimp are in the Chinese restaurant's Kung Pao Shrimp?", a: "11" },
    { q: "The Larry David sandwich contains whitefish, capers, onions, cream cheese, and which other smoked fish?", a: "Sable" },
    { q: "Who is the Yankees player on Larry's childhood jersey that goes missing?", a: "Joe Pepitone" },
    { q: "Why are Larry and Cheryl asked to leave Gil Thilander's house?", a: "Larry breaks a lamp" },
    { q: "What does Larry throw away in another man's garbage can?", a: "An apple core" },
    { q: "What is Richard Lewis's girlfriend allergic to?", a: "Peanuts" },
    { q: "What does the acupuncturist send Larry that leads him to not return?", a: "Flowers" },
    { q: "What does Larry accidentally give the maitre d' to bribe him for an immediate table?", a: "Cheryl's prescription" },
    { q: "What does Larry say his name is at the incest survivors group?", a: "Todd" },
    { q: "In what year did Curb Your Enthusiasm premiere?", a: "2000" },
    { q: "What is the name of the show's theme song?", a: "Frolic" },
    { q: "What is the surname of the family that moves in after a hurricane?", a: "Black" },
    { q: "In 'The Doll,' what does Larry cut off a child's doll?", a: "Its hair" },
    { q: "What is the name of the restaurant Larry, Jeff, and Ted open in season 3?", a: "Bobo's" },
    { q: "In the season 3 restaurant opening, the chef suffers from what condition?", a: "Tourette's syndrome" },
    { q: "In 'Trick or Treat,' Larry is called a self-loathing Jew for humming which composer?", a: "Wagner" },
    { q: "What spite coffee shop does Larry open next to Mocha Joe's in season 10?", a: "Latte Larry's" },
    { q: "In season 10, Larry wears what hat as a 'people repellent'?", a: "A MAGA hat" },
    { q: "In season 9, Larry writes a musical about the fatwa against which author?", a: "Salman Rushdie" },
    { q: "In 'Beloved Aunt,' a printing error swaps the word 'aunt' for what?", a: "cunt" },
    { q: "In season 4, Larry is cast in a Broadway production of which musical?", a: "The Producers" },
    { q: "What role does Larry play in 'The Producers'?", a: "Max Bialystock" },
    { q: "Who casts Larry in 'The Producers,' secretly hoping he'll flop?", a: "Mel Brooks" },
    { q: "What illness is Loretta diagnosed with in season 7?", a: "Cancer" },
    { q: "In the fictional reunion, George gets rich from an app called what?", a: "iToilet" },
    { q: "In the finale, Larry is arrested for giving water to someone waiting to do what?", a: "Vote" },
    { q: "In which city does Larry stand trial in the final season?", a: "Atlanta" },
    { q: "Wanda Sykes's rapper fiancé in season 3 goes by what name?", a: "Krazee-Eyez Killa" },
    { q: "Leon nicknames Larry's wheelchair-using girlfriend a what?", a: "A 'wheelie'" },
    { q: "What is the name of the coffee shop owner Larry feuds with in season 10?", a: "Mocha Joe" },
    { q: "What tennis star does Karry drive around in a limo?", a: "'John McEnroe'" },
    { q: "While Jeff is driving his parents and talking to Larry on Speakerphone, what term does Larry use to refer to Cheryl that leaves Jeff's parents outraged?", a: "Hitler" },
    { q: "After a mix-up over which night it was actually happening, Larry ends up attending this event with Mary's mother instead of Ted and Mary in their luxury box.", a: "Paul Simon Concert" },
    { q: "What article of clothing does Larry have stolen at the bowling alley?", a: "Shoes" },
    { q: "What does Jeff ask Larry to retrieve from his house while he undergos a bypass surgery?", a: "Porn Stash" },
    { q: "At Gil Thilander's party, what does Larry break that leads to Larry and Cheryl being asked to leave?", a: "Lamp" },
    { q: "What is Larry attemping to buy at a jewelry store to make amends with Cheryl when he is denied entry due to his appearance?", a: "Platinum and Diamond bracelet" },
    { q: "Why does Larry fire the interior decorator?", a: "She refuses to give him Diane Keaton's phone number (even though Diane attempted to leave her number on the answering machine)" },
    { q: "Who does David's neighbor Dean insist on meeting before he will sign anything to bury the telephone wire?", a: "Julia Louis-Dreyfus" },
    { q: "Larry causes road rage by confusing the double honk in what company radio commercial for the car behind them?", a: "AAMCO" },
    { q: "What is the name of Elizabeth Bank's cat?", a: "Mr. Noodle" },
    { q: "What name does Larry give at the incest survivor group?", a: "Todd" },
    { q: "What is the name of the doll whose haircut Larry is blamed for ruining?", a: "Judy" }
  ]

};